Repository lexicongovernance/pluraltools-backend, pull requests merged in 2024-01, with the labels that each got.

#46 fix default for getVoteForOptionByUser
  src/services/users.ts
Labels: bug

#47 add forumQuestion table
  migrations/0003_spooky_forge.sql
  migrations/0004_spotty_dragon_man.sql
  migrations/meta/0003_snapshot.json
  migrations/meta/0004_snapshot.json
  migrations/meta/_journal.json
  src/db/cycles.ts
  src/db/forumQuestions.ts
  src/db/index.ts
  src/db/questionOptions.ts
  src/db/votes.ts
  src/services/cycles.ts
  src/services/users.spec.ts
Labels: enhancement

#53 get votes by cycle
  src/routers/users.ts
  src/services/users.spec.ts
  src/services/users.ts
Labels: enhancement

#54 fix get votes per cycle params
  src/services/users.spec.ts
  src/services/users.ts
Labels: bug

#56 respond nonce request with data key in body
  src/services/auth/zupass.ts
Labels: bug

#60 Update route path for getting user votes
  src/routers/users.ts
Labels: bug

#61 Fix jest configuration
  jest.config.js
Labels: bug

#62 Fix bug when the array of votes is zero
  src/modules/plural_voting.test.ts
  src/services/votes.ts
Labels: bug

#63 Add groups router to API
  src/routers/api.ts
Labels: enhancement

#64 Fix update users endpoint
  src/routers/users.ts
  src/services/users.ts
  src/services/usersToGroups.ts
Labels: bug

#68 Add getEventCycles endpoint to events router
  src/routers/cycles.ts
  src/routers/events.ts
  src/services/cycles.ts
  src/services/events.ts
Labels: enhancement

#69 Refactor variable assignments in getResultStatistics function
  src/services/resultsPage.ts
Labels: enhancement

#74 Fix tests
  src/services/users.ts
Labels: bug

#76 Revert forum questions endpoint
  src/routers/users.ts
  src/services/users.ts
Labels: bug

#77 Update drizzle-kit version
  package.json
  pnpm-lock.yaml
Labels: enhancement

#79 Add userAttributes table and relation
  migrations/0001_many_captain_britain.sql
  migrations/meta/0001_snapshot.json
  migrations/meta/_journal.json
  src/db/index.ts
  src/db/userAttributes.ts
  src/db/users.ts
Labels: enhancement

#81 Add getUserAttributes endpoint to users router
  src/routers/users.ts
  src/services/userAttributes.ts
  src/services/users.ts
  src/types/users.ts
Labels: enhancement

#66 Add database seeding scripts and update dependencies
  README.md
  package.json
  pnpm-lock.yaml
  scripts/seed.ts
  src/services/registrations.spec.ts
  src/services/votes.ts
  src/utils/db/createDbPool.ts
  src/utils/db/seed.ts
Labels: enhancement

#98 Update release configuration and package version
  RELEASE.md
  package.json
  release.config.cjs
Labels: enhancement

#99 Remove cycles_enum and just use string
  migrations/0003_gigantic_black_bolt.sql
  migrations/meta/0003_snapshot.json
  migrations/meta/_journal.json
  src/db/cycles.ts
Labels: enhancement

#101 Add image_url column to events table
  migrations/0001_stiff_paibok.sql
  migrations/meta/0001_snapshot.json
  migrations/meta/_journal.json
  src/db/events.ts
Labels: enhancement

#113 Diego/hotfix versioning
  .github/workflows/deploy-development.yml
  .github/workflows/deploy-production.yml
  RELEASE.md
  migrations/0002_tan_archangel.sql
  migrations/meta/0002_snapshot.json
  migrations/meta/_journal.json
  package.json
  pnpm-lock.yaml
  release.config.cjs
  src/db/events.ts
Labels: bug

#109 Stop allowing voting on closed cycle
  jest.config.js
  package.json
  pnpm-lock.yaml
  release.config.js
  src/services/votes.spec.ts
  src/services/votes.ts
  src/types/cycles.ts
  src/utils/db/seed.ts
Labels: enhancement

#117 Add automated release process documentation
  RELEASE.md
Labels: documentation, minor

#118 Update workflows and seed script
  .github/workflows/deploy-development.yml
  .github/workflows/deploy-production.yml
  package.json
  scripts/workflows/bump-version.sh
Labels: minor

#124 Diego/fix bump script authentication
  scripts/workflows/bump-version.sh
Labels: minor

#125 Diego/fix bump script authentication
  .github/workflows/deploy-development.yml
  .github/workflows/deploy-production.yml
  scripts/workflows/bump-version.sh
Labels: minor

#128 patch update for gh actions
  .github/workflows/deploy-development.yml
  .github/workflows/deploy-production.yml
Labels: patch

#129 update develop with main actions
  .github/workflows/deploy-development.yml
  .github/workflows/deploy-production.yml
Labels: patch

#130 attempt to fix actions
  .github/workflows/deploy-development.yml
  .github/workflows/deploy-production.yml
Labels: patch

#134 Fix federated credentials
  migrations/0000_rich_sunfire.sql
  migrations/0001_talented_bill_hollister.sql
  migrations/0002_chief_swarm.sql
  migrations/0002_tan_archangel.sql
  migrations/meta/0000_snapshot.json
  migrations/meta/0001_snapshot.json
  migrations/meta/0002_snapshot.json
  migrations/meta/_journal.json
  package.json
  src/db/federatedCredentials.ts
  src/db/users.ts
  src/services/auth/zupass.ts
Labels: bug

#108 Prerelease v1.0.0
  .gitignore
  assets/groups.example.csv
  migrations/0000_rich_sunfire.sql
  migrations/0001_dusty_corsair.sql
  migrations/0001_stiff_paibok.sql
  migrations/0002_tan_archangel.sql
  migrations/0002_tiny_trish_tilby.sql
  migrations/meta/0000_snapshot.json
  migrations/meta/0001_snapshot.json
  migrations/meta/0002_snapshot.json
  migrations/meta/_journal.json
  package.json
  pnpm-lock.yaml
  scripts/db/insertCustomGroups.ts
  src/db/events.ts
  src/db/federatedCredentials.ts
  src/db/forumQuestions.ts
  src/db/groups.ts
  src/db/questionOptions.ts
  src/db/registrationData.ts
  src/db/registrationFieldOptions.ts
  src/db/registrationFields.ts
  src/db/registrations.ts
  src/db/userAttributes.ts
  src/db/users.ts
  src/services/auth/zupass.ts
  src/services/registrationData.ts
  src/services/registrations.ts
  src/services/users.spec.ts
  src/utils/db/insertCustomGroups.ts
  src/utils/db/seed.ts
Labels: DO NOT MERGE, major
