Repository lexicongovernance/pluraltools-backend, pull requests merged in 2024-02, with the labels that each got.

#140 Custom character validation
  migrations/0003_absurd_cobalt_man.sql
  migrations/meta/0003_snapshot.json
  migrations/meta/_journal.json
  src/db/registrationFields.ts
Labels: minor

#143 Add event registration description
  migrations/0004_typical_lily_hollister.sql
  migrations/meta/0004_snapshot.json
  migrations/meta/_journal.json
  src/db/events.ts
Labels: minor

#147 Fix post deployment workflows
  .github/workflows/deploy-development.yml
  .github/workflows/deploy-production.yml
Labels: bug

#146 Improve zupass login
  src/routers/auth.ts
  src/services/auth/zupass.ts
  src/types/auth.ts
  src/types/index.ts
Labels: feature, minor

#149 Add dependency installation step to deployment workflows (#147)
  .github/workflows/deploy-development.yml
  .github/workflows/deploy-production.yml
Labels: patch

#153 Add email column and name and make it updatable
  migrations/0005_goofy_northstar.sql
  migrations/meta/0005_snapshot.json
  migrations/meta/_journal.json
  src/db/users.ts
  src/services/users.ts
Labels: minor

#151 Remove cookie password
  .env.example
  src/index.ts
  src/routers/api.ts
  src/types/environment.ts
Labels: minor

#156 Update cookie password example
  .env.example
Labels: documentation

#159 adjust function overwriteRegistrationData
  src/services/registrationData.ts
  src/services/registrations.spec.ts
  src/services/registrations.ts
Labels: minor

#164 Refactor database seeding and group insertion scripts
  package.json
  pnpm-lock.yaml
  scripts/db/insertCustomGroups.ts
  scripts/db/seed.ts
  src/utils/db/insertCustomGroups.ts
  src/utils/db/seed.ts
Labels: bug, patch

#180 Update pnpm deprecated scripts
  package.json
  pnpm-lock.yaml
Labels: bug

#185 likes table
  DATABASE.md
  README.md
  migrations/0007_stormy_human_fly.sql
  migrations/meta/0007_snapshot.json
  migrations/meta/_journal.json
  src/db/comments.ts
  src/db/index.ts
  src/db/likes.ts
  src/db/users.ts
Labels: feature

#188 187 add option router
  src/routers/api.ts
  src/routers/options.ts
  src/services/options.ts
Labels: feature

#186 likes service
  src/routers/api.ts
  src/routers/comments.ts
  src/services/likes.ts
Labels: feature

#189 update save votes endpoint
  migrations/0008_heavy_the_hunter.sql
  migrations/meta/0008_snapshot.json
  migrations/meta/_journal.json
  src/db/questionOptions.ts
  src/routers/api.ts
  src/routers/cycles.ts
  src/routers/users.ts
  src/routers/votes.ts
  src/services/users.spec.ts
  src/services/users.ts
  src/services/votes.spec.ts
  src/services/votes.ts
Labels: feature, minor

#191 Remove positive check on votes
  src/services/votes.ts
Labels: bug, patch

#194 fix result page query
  src/services/resultsPage.ts
Labels: bug, patch

#196 fix subquery
  src/services/votes.ts
Labels: bug, minor

#199 Add statistics to results page
  src/services/resultsPage.ts
Labels: minor

#200 feat: allow seed scripts to work with ui constraints
  src/utils/db/seed.ts
Labels: feature

#211 Register title and subtitle
  migrations/0009_misty_storm.sql
  migrations/meta/0009_snapshot.json
  migrations/meta/_journal.json
  src/db/questionOptions.ts
  src/db/registrationFields.ts
  src/services/registrationData.ts
  src/services/registrations.ts
Labels: patch

#214 Add getUserOptions endpoint to users router
  src/routers/users.ts
  src/services/options.ts
Labels: feature

#218 Add username to comments endpoint
  migrations/meta/_journal.json
  src/services/comments.ts
Labels: patch

#219 Add userId to questionOptions
  migrations/0010_great_lord_tyger.sql
  migrations/meta/0010_snapshot.json
  migrations/meta/_journal.json
  src/db/questionOptions.ts
  src/db/users.ts
  src/services/registrationData.ts
  src/services/registrations.ts
Labels: feature

#223 Diego/fix comments query
  src/services/comments.ts
Labels: bug

#227 Add getUserRegistrations endpoint to users router
  src/routers/users.ts
  src/services/registrations.ts
Labels: feature

#229 Notifications tables
  migrations/0011_handy_night_thrasher.sql
  migrations/meta/0011_snapshot.json
  migrations/meta/_journal.json
  src/db/index.ts
  src/db/notificationTypes.ts
  src/db/users.ts
  src/db/usersToNotifications.ts
Labels: feature

#220 implement test coverage reports
  jest.config.js
  package.json
Labels: feature
