Repository lexicongovernance/pluraltools-backend, pull requests merged in 2024-03, with the labels that each got.

#231 improve middleware
  src/middleware/isLoggedIn.ts
  src/routers/comments.ts
  src/routers/cycles.ts
  src/routers/events.ts
  src/routers/forumQuestions.ts
  src/routers/groups.ts
  src/routers/options.ts
  src/routers/users.ts
Labels: bug

#230 Delete comment functionality
  src/routers/options.ts
  src/services/comments.ts
Labels: feature

#228 v2.2.0
  jest.config.js
  migrations/0011_handy_night_thrasher.sql
  migrations/meta/0011_snapshot.json
  migrations/meta/_journal.json
  package.json
  src/db/index.ts
  src/db/notificationTypes.ts
  src/db/users.ts
  src/db/usersToNotifications.ts
  src/middleware/isLoggedIn.ts
  src/routers/comments.ts
  src/routers/cycles.ts
  src/routers/events.ts
  src/routers/forumQuestions.ts
  src/routers/groups.ts
  src/routers/options.ts
  src/routers/users.ts
  src/services/comments.ts
  src/services/registrations.ts
Labels: minor

#234 Bug fixes
  .github/workflows/check-formatting.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  jest.config.js
  src/services/users.ts
Labels: bug

#233 Add users and groups to cycle endpoint
  src/routers/forumQuestions.ts
  src/services/cycles.spec.ts
  src/services/cycles.ts
  src/services/forumQuestions.spec.ts
  src/services/registrations.spec.ts
  src/services/statistics.spec.ts
  src/services/statistics.ts
Labels: feature

#235 Next v2.2.0
  .github/workflows/check-formatting.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  jest.config.js
  migrations/0011_handy_night_thrasher.sql
  migrations/meta/0011_snapshot.json
  migrations/meta/_journal.json
  package.json
  src/db/index.ts
  src/db/notificationTypes.ts
  src/db/users.ts
  src/db/usersToNotifications.ts
  src/middleware/isLoggedIn.ts
  src/routers/comments.ts
  src/routers/cycles.ts
  src/routers/events.ts
  src/routers/forumQuestions.ts
  src/routers/groups.ts
  src/routers/options.ts
  src/routers/users.ts
  src/services/comments.ts
  src/services/cycles.spec.ts
  src/services/cycles.ts
  src/services/forumQuestions.spec.ts
  src/services/registrations.spec.ts
  src/services/registrations.ts
  src/services/resultsPage.spec.ts
  src/services/resultsPage.ts
  src/services/statistics.spec.ts
  src/services/statistics.ts
  src/services/users.ts
Labels: DO NOT MERGE

#247 Update user service to check for existing email and username
  src/services/users.ts
  src/types/users.ts
Labels: patch

#249 backmerge v2.2.1
  src/services/users.ts
  src/types/users.ts
Labels: feature

#250 Diego/fix null values interpreted as duplicated
  .github/workflows/deploy-production.yml
  src/services/users.ts
Labels: bug

#258 Add first name and last name
  migrations/0012_loving_lenny_balinger.sql
  migrations/meta/0012_snapshot.json
  migrations/meta/_journal.json
  src/db/users.ts
  src/services/users.ts
  src/types/users.ts
Labels: patch

#261 Add first name and last name to cycle route
  src/services/cycles.ts
Labels: feature

#269 fix likes services db queries
  src/services/likes.ts
Labels: patch

#255 Next v2.3.0
  src/services/comments.ts
  src/services/likes.ts
  src/services/registrationData.spec.ts
  src/services/registrationData.ts
  src/services/statistics.spec.ts
  src/services/votes.spec.ts
  src/services/votes.ts
  src/utils/db/seed.ts
Labels: minor

#278 Add telegram to user
  migrations/0013_grey_the_anarchist.sql
  migrations/meta/0013_snapshot.json
  migrations/meta/_journal.json
  src/db/users.ts
  src/services/users.ts
Labels: patch
