Repository lexicongovernance/pluraltools-backend, pull requests merged in 2024-04, with the labels that each got.

#285 Add user schema test and update insertUserSchema
  src/services/users.spec.ts
  src/types/users.ts
Labels: patch

#307 Add group id to registrations
  assets/groups.example.csv
  migrations/0015_shiny_black_knight.sql
  migrations/meta/0015_snapshot.json
  migrations/meta/_journal.json
  scripts/db/insertCustomGroups.ts
  src/db/groups.ts
  src/db/registrations.ts
  src/handlers/events.ts
  src/handlers/groups.ts
  src/handlers/registrations.ts
  src/routers/events.ts
  src/routers/groups.ts
  src/routers/registrations.ts
  src/services/registrationData.spec.ts
  src/services/registrations.spec.ts
  src/services/registrations.ts
Labels: feature

#313 Add secret code service
  migrations/0016_ambitious_rictor.sql
  migrations/meta/0016_snapshot.json
  migrations/meta/_journal.json
  src/db/groupCategories.ts
  src/db/groups.ts
  src/handlers/groupCategories.ts
  src/handlers/groups.ts
  src/handlers/usersToGroups.ts
  src/routers/api.ts
  src/routers/groupCategories.ts
  src/routers/groups.ts
  src/routers/usersToGroups.ts
  src/services/groupCategories.spec.ts
  src/services/groupCategories.ts
  src/services/groups.spec.ts
  src/services/groups.ts
  src/types/groups.ts
  src/types/usersToGroups.ts
Labels: feature

#318 Fix registrations creating new groups
  src/handlers/groupCategories.ts
  src/handlers/groups.ts
  src/routers/groupCategories.ts
  src/utils/db/insertCustomGroups.ts
  src/utils/db/seed.ts
Labels: bug

#309 Next v2.5.0
  assets/groups.example.csv
  migrations/0015_shiny_black_knight.sql
  migrations/0016_ambitious_rictor.sql
  migrations/meta/0015_snapshot.json
  migrations/meta/0016_snapshot.json
  migrations/meta/_journal.json
  scripts/db/insertCustomGroups.ts
  src/db/forumQuestions.ts
  src/db/groupCategories.ts
  src/db/groups.ts
  src/db/index.ts
  src/db/questionsToGroupCategories.ts
  src/db/registrations.ts
  src/handlers/events.ts
  src/handlers/groupCategories.ts
  src/handlers/groups.ts
  src/handlers/registrations.ts
  src/handlers/users.ts
  src/handlers/usersToGroups.ts
  src/routers/api.ts
  src/routers/events.ts
  src/routers/groupCategories.ts
  src/routers/groups.ts
  src/routers/registrations.ts
  src/routers/usersToGroups.ts
  src/services/groupCategories.spec.ts
  src/services/groupCategories.ts
  src/services/groups.spec.ts
  src/services/groups.ts
  src/services/registrationData.spec.ts
  src/services/registrations.spec.ts
  src/services/registrations.ts
  src/services/statistics.spec.ts
  src/services/votes.spec.ts
  src/services/votes.ts
  src/types/groups.ts
  src/types/usersToGroups.ts
  src/utils/db/insertCustomGroups.ts
  src/utils/db/seed.ts
Labels: minor

#323 Diego/hide fields on group registration
  migrations/0017_jazzy_revanche.sql
  migrations/meta/0017_snapshot.json
  migrations/meta/_journal.json
  src/db/registrationFields.ts
  src/handlers/groupCategories.ts
  src/routers/api.ts
Labels: feature

#328 Add alerts
  migrations/0018_abandoned_mongoose.sql
  migrations/meta/0018_snapshot.json
  migrations/meta/_journal.json
  src/db/alerts.ts
  src/db/index.ts
  src/handlers/alerts.ts
  src/routers/alerts.ts
  src/routers/api.ts
Labels: feature

#329 fix build command
  src/routers/groups.ts
Labels: bug

#330 Seed a secret group
  src/utils/db/seed.ts
Labels: improvement

#331 fix: groupid not being saved on group registrations
  src/handlers/events.ts
  src/handlers/registrations.ts
  src/services/registrations.ts
Labels: bug

#338 add for_user and for_group in registration field
  migrations/0019_nifty_wallow.sql
  migrations/meta/0019_snapshot.json
  migrations/meta/_journal.json
  src/db/registrationFields.ts
  src/handlers/registrations.ts
  src/services/registrationFields.spec.ts
  src/services/registrationFields.ts
  src/utils/db/seed.ts
Labels: feature

#339 Limit one registration per group
  src/handlers/registrations.ts
  src/services/registrations.ts
Labels: feature

#342 adds better validation for fields and register field options in seed
  src/services/registrationFields.ts
  src/utils/db/seed.ts
Labels: feature
