Repository lexicongovernance/pluraltools-backend, pull requests merged in 2024-07, with the labels that each got.

#434 rename db tables to have more consistency
  .github/workflows/check-formatting.yml
  .github/workflows/deploy-development.yml
  .github/workflows/deploy-production.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  migrations/0027_stormy_silverclaw.sql
  migrations/meta/0027_snapshot.json
  migrations/meta/_journal.json
  src/db/comments.ts
  src/db/cycles.ts
  src/db/index.ts
  src/db/options.ts
  src/db/questions-to-group-categories.ts
  src/db/questions.ts
  src/db/users.ts
  src/db/votes.ts
  src/handlers/comments.ts
  src/handlers/cycles.ts
  src/handlers/events.ts
  src/handlers/options.ts
  src/handlers/questions.ts
  src/handlers/users.ts
  src/routers/api.ts
  src/routers/questions.ts
  src/services/comments.spec.ts
  src/services/comments.ts
  src/services/cycles.spec.ts
  src/services/cycles.ts
  src/services/funding-mechanism.ts
  src/services/statistics.spec.ts
  src/services/statistics.ts
  src/services/votes.spec.ts
  src/services/votes.ts
  src/utils/db/seed-data-generators.ts
  src/utils/db/seed.ts
Labels: improvement

#442 Migrate to jsonb
  migrations/0028_green_gamora.sql
  migrations/0029_colorful_psynapse.sql
  migrations/meta/0028_snapshot.json
  migrations/meta/0029_snapshot.json
  migrations/meta/_journal.json
  src/db/events.ts
  src/db/groups.ts
  src/db/options.ts
  src/db/questions.ts
  src/db/registrations.ts
  src/handlers/cycles.ts
  src/handlers/events.ts
  src/handlers/registrations.ts
  src/services/cycles.ts
  src/services/forum-questions.ts
  src/services/registration-data.spec.ts
  src/services/registration-data.ts
  src/services/registration-fields.spec.ts
  src/services/registration-fields.ts
  src/services/registrations.spec.ts
  src/services/registrations.ts
  src/services/statistics.ts
  src/services/validation.spec.ts
  src/services/validation.ts
  src/types/index.ts
  src/types/options.ts
  src/types/registrations.ts
  src/types/validation.ts
  src/utils/db/seed-data-generators.ts
  src/utils/db/seed.ts
Labels: feature

#443 Add api routes for options
  migrations/0029_quick_ares.sql
  migrations/meta/0029_snapshot.json
  migrations/meta/_journal.json
  src/db/questions.ts
  src/handlers/options.ts
  src/handlers/questions.ts
  src/handlers/registrations.ts
  src/routers/options.ts
  src/services/groups.spec.ts
  src/services/groups.ts
  src/services/options.ts
  src/services/questions.spec.ts
  src/services/questions.ts
  src/services/registrations.spec.ts
  src/services/registrations.ts
Labels: feature

#445 update test coverage
  src/services/funding-mechanism.spec.ts
  src/services/funding-mechanism.ts
  src/services/users.spec.ts
  src/services/users.ts
Labels: improvement

#447 add group categories to events
  .github/workflows/check-formatting.yml
  .github/workflows/deploy-development.yml
  .github/workflows/deploy-production.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  src/db/events.ts
Labels: easy

#450 update fields structure to dict
  migrations/0028_chilly_sentry.sql
  migrations/0028_green_gamora.sql
  migrations/0029_quick_ares.sql
  migrations/0030_polite_forge.sql
  migrations/meta/0028_snapshot.json
  migrations/meta/0029_snapshot.json
  migrations/meta/0030_snapshot.json
  migrations/meta/_journal.json
  src/db/schema/events.ts
  src/db/schema/questions.ts
  src/db/seed.ts
  src/services/validation.spec.ts
  src/services/validation.ts
  src/types/validation.ts
Labels: feature

#451 add registration to seed
  src/db/seed.ts
Labels: feature

#452 add status to events
  migrations/0029_outgoing_true_believers.sql
  migrations/meta/0029_snapshot.json
  migrations/meta/_journal.json
  src/db/schema/cycles.ts
  src/handlers/events.ts
Labels: feature

#454 update alerts to navlinks
  migrations/0029_mushy_vermin.sql
  migrations/meta/0029_snapshot.json
  migrations/meta/_journal.json
  src/db/schema/events.ts
  src/db/schema/index.ts
  src/db/schema/nav-links.ts
  src/handlers/alerts.ts
  src/handlers/events.ts
  src/handlers/nav-links.ts
  src/routers/api.ts
  src/routers/events.ts
  src/routers/nav-links.ts
Labels: feature
